POST https://be-node.onrender.com/wallet/fogot_password HTTP/1.1
content-type: application/json

{
  "private_key": "0x9bc6e32a97852c0d262d43704cfdbdfff72020eb",
  "new_password": "Thuan12312w
}
